config {
    type: "table"
}

select
* except (next_event_timestamp)
,div(ifnull(timestamp_diff(next_event_timestamp,event_timestamp, microsecond),0),1000000) time_to_next_event_timestamp_sec
from
(select 
*
,if(page is not null,lead(event_timestamp) over (partition by user_pseudo_id, unique_session_id, page is not null order by event_timestamp asc, event_name asc),null) next_event_timestamp
from ${ref("events_ga4_stg02_with_page_categories")}
)
