config {
    type: "operations",
    name: "fb_expected",
    schema: `${settings.tests_dataset}`
}
create schema if not exists ${settings.tests_dataset} ;
CREATE OR REPLACE EXTERNAL TABLE
  ${settings.tests_facebook_ads_expected_table} OPTIONS ( format = 'GOOGLE_SHEETS',
    skip_leading_rows = ${settings.tests_facebook_ads_expected_table_skip_leading_rows},
    uris = ['${settings.tests_facebook_ads_expected_table_url}'])
